name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - marc/update # remove me

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run format-check
      - run: npm run lint
      - run: npm run build
      - run: npm run package
      - run: npm test
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Netbob.xcresult
        uses: ./
        with:
          path: __tests__/fixtures/Netbob.xcresult
          title: Netbob.xcresult
      - name: Weather.xcresult
        uses: ./
        with:
          path: __tests__/fixtures/Weather.xcresult
          title: Weather.xcresult
      - name: Weather.xcresult (+passed)
        uses: ./
        with:
          path: __tests__/fixtures/Weather.xcresult
          title: Weather.xcresult (+passed)
          show-passed-tests: true
      - name: Weather.xcresult (+test summaries)
        uses: ./
        with:
          path: __tests__/fixtures/Weather.xcresult
          title: Weather.xcresult (+test summaries)
          show-test-summaries: true
      - name: KeychainAccess.xcresult
        uses: ./
        with:
          path: __tests__/fixtures/KeychainAccess.xcresult
          title: KeychainAccess.xcresult
      - name: KeychainAccess.xcresult (+passed)
        uses: ./
        with:
          path: __tests__/fixtures/KeychainAccess.xcresult
          title: KeychainAccess.xcresult (+passed)
          show-passed-tests: true
      - name: TAU.xcresult
        uses: ./
        with:
          path: __tests__/fixtures/TAU.xcresult
          title: TAU.xcresult
      - name: TestResults.xcresult
        uses: ./
        with:
          path: __tests__/fixtures/TestResults.xcresult
          title: TestResults.xcresult
      - name: Coverage.xcresult
        uses: ./
        with:
          path: __tests__/fixtures/Coverage.xcresult
          title: Coverage.xcresult
      - name: Coverage.xcresult (-coverage)
        uses: ./
        with:
          path: __tests__/fixtures/Coverage.xcresult
          title: Coverage.xcresult (-coverage)
          show-code-coverage: false
      - name: UhooiPicBook.xcresult
        uses: ./
        with:
          path: __tests__/fixtures/UhooiPicBook.xcresult
          title: UhooiPicBook.xcresult
      - name: UhooiPicBook.xcresult (+passed)
        uses: ./
        with:
          path: __tests__/fixtures/UhooiPicBook.xcresult
          title: UhooiPicBook.xcresult (+passed)
          show-passed-tests: true
      - name: UhooiPicBook.xcresult (-coverage)
        uses: ./
        with:
          path: __tests__/fixtures/UhooiPicBook.xcresult
          title: UhooiPicBook.xcresult (-coverage)
          show-code-coverage: false
      - name: Multiple Xcode Results
        uses: ./
        with:
          path: |
            __tests__/fixtures/Weather.xcresult
            __tests__/fixtures/KeychainAccess.xcresult
            __tests__/fixtures/TAU.xcresult
          title: 'Multiple Xcode Results'
